apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  namespace: todo-app
  labels:
    app: todo-backend
spec:
  containers:
  - name: backend
    image: idilsuelmas/todo-backend:v1
    envFrom:
    - configMapRef:
        name: db-config
    - secretRef:
        name: db-secret
    ports:
    - containerPort: 8080
