apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  namespace: todo-app
  labels:
    app: todo-db
spec:
  containers:
  - name: postgres
    image: postgres:15
    env:
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_USER
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_NAME
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASS
    ports:
    - containerPort: 5432
    # --- DOĞRU YER BURASI ---
    volumeMounts:
    - name: db-storage
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: db-storage
    persistentVolumeClaim:
      claimName: postgres-pvc
