apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: todo-app
  labels:
    app: todo-frontend
spec:
  containers:
  - name: frontend
    image: idilsuelmas/todo-frontend:v2
    ports:
    - containerPort: 80
