apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: {{ .Values.global.namespace }}
data:
  alert-rules.yml: |
    groups:
      - name: todo-app-alerts
        rules:
          - alert: HighRAMUsagePercent
            # (Kullanilan RAM / Limit) * 100 > 80
            expr: (sum(container_memory_usage_bytes{namespace="todo-app"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace="todo-app"}) by (pod)) * 100 > 80
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Yüksek RAM Kullanimi (%80+)"
              description: "Pod {{ $labels.pod }} kapasitesinin %80'inden fazlasini kullaniyor."
