# 1. Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.deploymentName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.prometheus.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.appName }}
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.prometheus.image }}:{{ .Values.prometheus.imageTag }}"
        imagePullPolicy: {{ .Values.prometheus.pullPolicy | default "Always" }}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/
        ports:
        - containerPort: 9090
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
---
# 2. Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: {{ .Values.prometheus.appName }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: {{ .Values.prometheus.service.targetPort }}
    nodePort: {{ .Values.prometheus.service.nodePort }}
---
# 3. Prometheus ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
       
