# 1. Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.deploymentName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.prometheus.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.appName }}
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest  # Prometheus'un resmi Docker imajı kullanılıyor.
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"  # ConfigMap ile sağlanan yapılandırma dosyası belirtiliyor.
        ports:
        - containerPort: 9090  # Prometheus web arayüzü için kullanılan port.
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus  # ConfigMap içeriğinin bağlandığı dizin.
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config  # ConfigMap kullanılarak yapılandırma dosyası bağlanıyor.
---
# 2. Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: {{ .Values.prometheus.appName }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: {{ .Values.prometheus.service.targetPort }}
    nodePort: {{ .Values.prometheus.service.nodePort }}
---
# 3. Prometheus ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Metriklerin her 15 saniyede bir toplanmasini sağlar.

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']  # Prometheus'un kendi metriklerini izlemesini sağlar.

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod  # Kubernetes pod'larini otomatik keşfetmek için kullanilir.
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true  # Pod'un annotation'larinda prometheus.io/scrape=true varsa, metrikleri alir.
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__  # Metriklerin hangi path üzerinden alinacagini belirler.
            regex: (.+)
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__  # Hedef adresi belirler.
            regex: (.+)
            replacement: $1
